"""Typed config models for the Hub Energie config flow."""

from __future__ import annotations

from typing import Any, Final, Literal, TypedDict

from .const import (
    CONF_BATTERY_SYSTEMS,
    CONF_BATT_ADVANCED,
    CONF_BATT_CAPACITY_KWH,
    CONF_BATT_CAPACITY_KWH_ENTITY,
    CONF_BATT_ENERGY_IN,
    CONF_BATT_ENERGY_OUT,
    CONF_BATT_MAX_CHARGE_W,
    CONF_BATT_MAX_CHARGE_W_ENTITY,
    CONF_BATT_MAX_DISCHARGE_W,
    CONF_BATT_MAX_DISCHARGE_W_ENTITY,
    CONF_BATT_NAME,
    CONF_BATT_POWER_IN,
    CONF_BATT_POWER_NET,
    CONF_BATT_POWER_NET_SIGN,
    CONF_BATT_POWER_OUT,
    CONF_BATT_SOC,
    CONF_BATT_SOC_MAX,
    CONF_BATT_SOC_MAX_ENTITY,
    CONF_BATT_SOC_MIN,
    CONF_BATT_SOC_MIN_ENTITY,
    CONF_CONTRACT_NAME,
    CONF_CONTRACT_POWER,
    CONF_CURRENCY,
    CONF_CURRENT_SLOT_SENSOR,
    CONF_ENERGY_PRICE,
    CONF_GRID_EXPORT_ENERGY,
    CONF_GRID_EXPORT_ENERGY_PHASES,
    CONF_GRID_IMPORT_ENERGY,
    CONF_GRID_IMPORT_ENERGY_PHASES,
    CONF_GRID_TRI_ENERGY_MODE,
    CONF_GRID_TRI_SENSOR_LAYOUT,
    CONF_GRID_POWER_PHASES,
    CONF_GRID_POWER_SENSOR,
    CONF_GRID_POWER_SIGN_MODE,
    CONF_HAS_BATTERIES,
    CONF_HAS_SOLAR,
    CONF_LOAD_POWER_SENSOR,
    CONF_PHASE_TYPE,
    CONF_PRICE_BASIS,
    CONF_PRICING_STRUCTURE,
    CONF_RTE_CLIENT_ID,
    CONF_RTE_CLIENT_SECRET,
    CONF_SCHEDULE_SLOTS,
    CONF_SOLAR_ENERGY,
    CONF_SOLAR_ESTIMATION_ENABLED,
    CONF_SOLAR_EXPORT_TARIFF,
    CONF_SOLAR_LOCATION_LAT,
    CONF_SOLAR_LOCATION_LON,
    CONF_SOLAR_ORIENTATION,
    CONF_SOLAR_PEAK_POWER,
    CONF_SOLAR_PERFORMANCE,
    CONF_SOLAR_POWER_SENSOR,
    CONF_SOLAR_RESALE_CONTRACT,
    CONF_SOLAR_SHADING,
    CONF_SOLAR_TILT,
    CONF_SOLAR_TILT_MODE,
    CONF_SUBSCRIPTION_PRICE,
    CONF_SUPPLIER,
    CONF_SUPPLIER_CUSTOM_NAME,
    CONF_TARIFF_MODE,
    CONF_TARIFF_OFFER,
    CONF_TARIFF_SOURCE,
    CONF_TEMPO_MODE,
    CONF_TOU_PERIODS,
    OPT_ABONNEMENT,
    OPT_BLEU_HC,
    OPT_BLEU_HP,
    OPT_BLANC_HC,
    OPT_BLANC_HP,
    OPT_FIXED_TTC,
    OPT_MAX_DELTA_KWH_BATTERY,
    OPT_MAX_DELTA_KWH_GRID,
    OPT_MAX_DELTA_KWH_OTHER,
    OPT_MAX_DELTA_KWH_SOLAR,
    OPT_REINJECTION_BATT_CHARGE_SIGNIFICANT_W,
    OPT_REINJECTION_BATT_FULL_MIN_SOC_FRAC,
    OPT_REINJECTION_EXPORT_IGNORE_BELOW_W,
    OPT_REINJECTION_EXPORT_MIN_ABS_W,
    OPT_REINJECTION_EXPORT_VS_SOLAR_FRACTION,
    OPT_REINJECTION_MIN_SOLAR_FOR_CLASSIFY_W,
    OPT_REINJECTION_SHORT_EXPORT_MAX_S,
    OPT_REINJECTION_SHORT_EXPORT_MAX_W,
    OPT_ROUGE_HC,
    OPT_ROUGE_HP,
    OPT_TARIFF_FETCHED_AT,
)

BATTERY_ID: Final = "id"

ValidationScope = Literal[
    "user",
    "supplier_custom",
    "tariff_mode",
    "contract",
    "edf_offer",
    "tempo_mode",
    "rte_credentials",
    "manual_pricing",
    "manual_flat",
    "manual_tou",
    "manual_schedule_form",
    "manual_schedule_json",
    "grid",
    "grid_tri_energy_mode",
    "grid_tri_per_phase",
    "grid_tri_layout",
    "tri_grid_phase_1",
    "tri_grid_phase_2",
    "tri_grid_phase_3",
    "grid_phases",
    "solar_toggle",
    "solar_config",
    "solar_options",
    "solar_estimation",
    "battery_toggle",
    "battery_add",
    "battery_advanced",
    "offer_options",
    "tariff_refresh",
]

BatterySystemDict = TypedDict(
    "BatterySystemDict",
    {
        BATTERY_ID: str,
        CONF_BATT_NAME: str,
        CONF_BATT_ENERGY_IN: str,
        CONF_BATT_ENERGY_OUT: str,
        CONF_BATT_POWER_IN: str,
        CONF_BATT_POWER_OUT: str,
        CONF_BATT_POWER_NET: str,
        CONF_BATT_POWER_NET_SIGN: str,
        CONF_BATT_SOC: str,
        CONF_BATT_CAPACITY_KWH: float,
        CONF_BATT_CAPACITY_KWH_ENTITY: str,
        CONF_BATT_MAX_CHARGE_W: float,
        CONF_BATT_MAX_CHARGE_W_ENTITY: str,
        CONF_BATT_MAX_DISCHARGE_W: float,
        CONF_BATT_MAX_DISCHARGE_W_ENTITY: str,
        CONF_BATT_SOC_MIN: float,
        CONF_BATT_SOC_MIN_ENTITY: str,
        CONF_BATT_SOC_MAX: float,
        CONF_BATT_SOC_MAX_ENTITY: str,
    },
    total=False,
)

HubEnergieConfigEntryData = TypedDict(
    "HubEnergieConfigEntryData",
    {
        CONF_SUPPLIER: str,
        CONF_SUPPLIER_CUSTOM_NAME: str,
        CONF_PHASE_TYPE: str,
        CONF_GRID_TRI_ENERGY_MODE: str,
        CONF_GRID_TRI_SENSOR_LAYOUT: str,
        CONF_TARIFF_MODE: str,
        CONF_CONTRACT_POWER: str,
        CONF_CONTRACT_NAME: str,
        CONF_TARIFF_OFFER: str,
        CONF_TEMPO_MODE: str,
        CONF_RTE_CLIENT_ID: str,
        CONF_RTE_CLIENT_SECRET: str,
        CONF_CURRENT_SLOT_SENSOR: str,
        CONF_PRICING_STRUCTURE: str,
        CONF_PRICE_BASIS: str,
        CONF_CURRENCY: str,
        CONF_TARIFF_SOURCE: str,
        CONF_ENERGY_PRICE: float,
        CONF_SUBSCRIPTION_PRICE: float,
        CONF_TOU_PERIODS: list[dict[str, Any]],
        CONF_SCHEDULE_SLOTS: list[dict[str, Any]],
        CONF_GRID_IMPORT_ENERGY: str,
        CONF_GRID_EXPORT_ENERGY: str,
        CONF_GRID_POWER_SENSOR: str,
        CONF_GRID_POWER_SIGN_MODE: str,
        CONF_LOAD_POWER_SENSOR: str,
        CONF_GRID_IMPORT_ENERGY_PHASES: list[dict[str, Any]],
        CONF_GRID_EXPORT_ENERGY_PHASES: list[dict[str, Any]],
        CONF_GRID_POWER_PHASES: list[dict[str, Any]],
        CONF_HAS_SOLAR: bool,
        CONF_SOLAR_ENERGY: str,
        CONF_SOLAR_POWER_SENSOR: str,
        CONF_SOLAR_RESALE_CONTRACT: bool,
        CONF_SOLAR_EXPORT_TARIFF: float,
        CONF_SOLAR_ESTIMATION_ENABLED: bool,
        CONF_SOLAR_LOCATION_LAT: float,
        CONF_SOLAR_LOCATION_LON: float,
        CONF_SOLAR_PEAK_POWER: float,
        CONF_SOLAR_ORIENTATION: float,
        CONF_SOLAR_TILT_MODE: str,
        CONF_SOLAR_TILT: float,
        CONF_SOLAR_SHADING: str,
        CONF_SOLAR_PERFORMANCE: str,
        CONF_HAS_BATTERIES: bool,
        CONF_BATTERY_SYSTEMS: list[BatterySystemDict],
    },
    total=False,
)

HubEnergieConfigEntryOptions = TypedDict(
    "HubEnergieConfigEntryOptions",
    {
        OPT_BLEU_HC: float,
        OPT_BLEU_HP: float,
        OPT_BLANC_HC: float,
        OPT_BLANC_HP: float,
        OPT_ROUGE_HC: float,
        OPT_ROUGE_HP: float,
        OPT_ABONNEMENT: float,
        OPT_FIXED_TTC: float,
        OPT_TARIFF_FETCHED_AT: str,
        OPT_MAX_DELTA_KWH_GRID: float,
        OPT_MAX_DELTA_KWH_SOLAR: float,
        OPT_MAX_DELTA_KWH_BATTERY: float,
        OPT_MAX_DELTA_KWH_OTHER: float,
        OPT_REINJECTION_EXPORT_IGNORE_BELOW_W: float,
        OPT_REINJECTION_BATT_CHARGE_SIGNIFICANT_W: float,
        OPT_REINJECTION_SHORT_EXPORT_MAX_S: float,
        OPT_REINJECTION_SHORT_EXPORT_MAX_W: float,
        OPT_REINJECTION_MIN_SOLAR_FOR_CLASSIFY_W: float,
        OPT_REINJECTION_EXPORT_MIN_ABS_W: float,
        OPT_REINJECTION_EXPORT_VS_SOLAR_FRACTION: float,
        OPT_REINJECTION_BATT_FULL_MIN_SOC_FRAC: float,
    },
    total=False,
)

HubEnergieConfigPartial = TypedDict(
    "HubEnergieConfigPartial",
    {
        CONF_SUPPLIER: str,
        CONF_SUPPLIER_CUSTOM_NAME: str | None,
        CONF_PHASE_TYPE: str,
        CONF_GRID_TRI_ENERGY_MODE: str | None,
        CONF_GRID_TRI_SENSOR_LAYOUT: str | None,
        CONF_TARIFF_MODE: str,
        CONF_CONTRACT_POWER: str,
        CONF_CONTRACT_NAME: str | None,
        CONF_TARIFF_OFFER: str,
        CONF_TEMPO_MODE: str,
        CONF_RTE_CLIENT_ID: str,
        CONF_RTE_CLIENT_SECRET: str,
        CONF_PRICING_STRUCTURE: str,
        CONF_PRICE_BASIS: str,
        CONF_CURRENCY: str,
        CONF_TARIFF_SOURCE: str,
        CONF_ENERGY_PRICE: float,
        CONF_SUBSCRIPTION_PRICE: float,
        CONF_TOU_PERIODS: list[dict[str, Any]],
        CONF_SCHEDULE_SLOTS: list[dict[str, Any]],
        CONF_GRID_IMPORT_ENERGY: str,
        CONF_GRID_EXPORT_ENERGY: str | None,
        CONF_GRID_POWER_SENSOR: str | None,
        CONF_GRID_POWER_SIGN_MODE: str,
        CONF_LOAD_POWER_SENSOR: str | None,
        CONF_GRID_IMPORT_ENERGY_PHASES: list[dict[str, Any]] | None,
        CONF_GRID_EXPORT_ENERGY_PHASES: list[dict[str, Any]] | None,
        CONF_GRID_POWER_PHASES: list[dict[str, Any]] | None,
        CONF_HAS_SOLAR: bool,
        CONF_SOLAR_ENERGY: str | None,
        CONF_SOLAR_POWER_SENSOR: str | None,
        CONF_SOLAR_RESALE_CONTRACT: bool,
        CONF_SOLAR_EXPORT_TARIFF: float | None,
        CONF_SOLAR_ESTIMATION_ENABLED: bool,
        CONF_SOLAR_LOCATION_LAT: float | None,
        CONF_SOLAR_LOCATION_LON: float | None,
        CONF_SOLAR_PEAK_POWER: float | None,
        CONF_SOLAR_ORIENTATION: float | None,
        CONF_SOLAR_TILT_MODE: str | None,
        CONF_SOLAR_TILT: float | None,
        CONF_SOLAR_SHADING: str | None,
        CONF_SOLAR_PERFORMANCE: str | None,
        CONF_HAS_BATTERIES: bool,
        CONF_BATTERY_SYSTEMS: list[BatterySystemDict],
        CONF_BATT_NAME: str,
        CONF_BATT_ENERGY_IN: str,
        CONF_BATT_ENERGY_OUT: str,
        CONF_BATT_POWER_IN: str | None,
        CONF_BATT_POWER_OUT: str | None,
        CONF_BATT_POWER_NET: str | None,
        CONF_BATT_POWER_NET_SIGN: str | None,
        CONF_BATT_SOC: str | None,
        CONF_BATT_CAPACITY_KWH: float | None,
        CONF_BATT_CAPACITY_KWH_ENTITY: str | None,
        CONF_BATT_MAX_CHARGE_W: float | None,
        CONF_BATT_MAX_CHARGE_W_ENTITY: str | None,
        CONF_BATT_MAX_DISCHARGE_W: float | None,
        CONF_BATT_MAX_DISCHARGE_W_ENTITY: str | None,
        CONF_BATT_SOC_MIN: float | None,
        CONF_BATT_SOC_MIN_ENTITY: str | None,
        CONF_BATT_SOC_MAX: float | None,
        CONF_BATT_SOC_MAX_ENTITY: str | None,
    },
    total=False,
)

FlowDraftDict = TypedDict(
    "FlowDraftDict",
    {
        "data": HubEnergieConfigEntryData,
        "options": HubEnergieConfigEntryOptions,
        CONF_BATT_ADVANCED: bool,
    },
    total=False,
)
